pokemon_battle/src/Entity/Dresseur.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DresseurRepository")
 */
class Dresseur implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $Nom;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\EquipePokemon", inversedBy="Dresseurs")
     * @ORM\JoinColumn(nullable=true)
     */
    private $equipePokemon;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->Nom;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = password_hash($password, PASSWORD_BCRYPT);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEquipePokemon(): ?EquipePokemon
    {
        return $this->equipePokemon;
    }

    public function setEquipePokemon(?EquipePokemon $equipePokemon): self
    {
        $this->equipePokemon = $equipePokemon;

        return $this;
    }

    public function __toString() 
    {
        return $this->Nom; 
    }
}

pokemon_battle/src/Controller/BackpackController.php
<?php

namespace App\Controller;

use App\Entity\Objects;
use App\Repository\ObjectsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/backpack")
 */
class BackpackController extends AbstractController
{
    /**
     * @Route("/", name="backpack_index", methods={"GET"})
     */
    public function index(ObjectsRepository $ObjectsRepository): Response
    {
        return $this->render('backpack/index.html.twig', [
            'backpack' => $ObjectsRepository->findAll(),
        ]);
    }
    /**
     * @Route("/id/{id}", name="backpack_show", methods={"GET"})
     */
    public function show(Objects $objects): Response
    {
        return $this->render('backpack/show.html.twig', [
            'objects' => $objects,
        ]);
    }
}

pokemon_battle/templates/backpack/index.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Backpack index{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}
        	<h1>Backpack index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Effet</th>
            </tr>
        </thead>
        <tbody>
        {% for backpack in backpack %}
            <tr>
                <td>{{ backpack.id }}</td>
                <td>{{ backpack.nom }}</td>
                <td>{{ backpack.effet }}</td>
                <td>
                    <a href="{{ path('backpack_show', {'id': backpack.id}) }}">show</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        {% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

pokemon_battle/templates/backpack/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Backpack{% endblock %}

{% block body %}
    <h1>Backpack</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Enable</th>
                <td>{{ objects.Enable ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ objects.CreatedAt ? objects.CreatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ objects.UpdatedAt ? objects.UpdatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DeletedAt</th>
                <td>{{ objects.DeletedAt ? objects.DeletedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ objects.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ objects.nom }}</td>
            </tr>
            <tr>
                <th>Effect</th>
                <td>{{ objects.effet }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('backpack_index') }}">back to list</a>

{% endblock %}